version: "3.3"

services: 
  postgres: 
    image: postgres:14
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=codetunes
    ports:
      - 5432:5432
    volumes: 
      - ./postgres_data:/var/lib/postgre/data